# Generated by Django 5.2.4 on 2025-07-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="picture",
            field=models.ImageField(upload_to="product_images"),
        ),
    ]
