# Generated by Django 5.2.4 on 2025-07-24 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_product_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="image",
        ),
    ]
